name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Confirm setup
      description: By submitting this issue, you confirm to have done the following in preparation:
      options:
        - label: I have installed the development version of `{gptstudio}` (`pak::pak("MichelNivard/gptstudio")`) and tested if the problem remains.
          required: true
        - label: I have installed the `{reprex}` and `{sessioninfo}` packages to be able to run this issue's code snippet `pak::pak(c("reprex", "sessioninfo"))`.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen? Be as verbose as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Tell us what you see!
      value: "I was trying to do X, and when I typed/clicked Y, I found the following problem:"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: sessioninfo
    attributes:
      label: Session info
      description: Please run `reprex::reprex(gptstudio::gptstudio_sitrep(), session_info = TRUE)` and paste the output here. It will provides us more context on your system.
      render: r
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MichelNivard/gptstudio?tab=coc-ov-file#).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
