name: Feature request
description: Make a case for a new feature.
title: "[FR]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: case
    attributes:
      label: What would you like to have?
      description: |
        Be as verbose as possible. You can use examples from other projects.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Let us know your thoughts!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MichelNivard/gptstudio?tab=coc-ov-file#).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
